/* SPDX-License-Identifier: (GPL-2.0 OR BSD-3-Clause) */
/*
 * Copyright(c) 2020 Intel Corporation.
 */
#ifndef RH82_COMPAT_H
#define RH82_COMPAT_H

#define CREATE_AH_HAS_UDATA
#define HAVE_ALLOC_RDMA_NETDEV
#define CREATE_FLOW_HAS_UDATA
#define HAVE_IB_GID_ATTR
#define ADD_GID_HAS_GID
#define HAVE_RDMA_NETDEV_GET_PARAMS
#define HAVE_ARRAY_SIZE
#define HAVE_NOSPEC_H
#define HAVE_ENUM_IB_UVERBS_ADVISE_MR_ADVICE
#define HAVE_IB_DEVICE_OPS
#define HAVE_IB_SET_DEVICE_OPS
#define POST_HAS_CONST
#define CREATE_AH_HAS_FLAGS
#define DESTROY_AH_HAS_FLAGS
#define HAVE_KMALLOC_ARRAY_NODE
#define HAVE_IBDEV_DRIVER_ID
#define HAVE_IB_GET_CACHED_SUBNET_PREFIX
#define HAVE_MAX_SEND_SGE
#define HAVE_SECURITY_H
#define HAVE_RDMA_SET_DEVICE_SYSFS_GROUP
#define HAVE_RDMA_DEVICE_TO_IBDEV
#define HAVE_VM_FAULT_T
#define HAVE_RDMA_COPY_AH_ATTR
#define HAVE_PCI_CORE_AER_CLEAR
#define HAVE_ATOMIC64_PINNED_VM
#define HAVE_PUT_USER_PAGES
#define HAVE_FS_CONTEXT
#define HAVE_UMEM_PTR_VALIDITY_CHECK
#define IB_DEVICE_OPS_DRIVER_ID
#define IB_DEVICE_OPS_OWNER
#define HAVE_NETDEV_XMIT_MORE
#define HAVE_SKB_FRAG_OFF
#define HAVE_CORE_ALLOC_CQ
#define HAVE_CORE_ALLOC_PD
#define DEALLOC_PD_HAS_UDATA
#define NO_IB_UCONTEXT
#define HAVE_CORE_ALLOC_UCONTEXT
#define HAVE_CORE_ALLOC_SRQ
#define DESTROY_CQ_HAS_UDATA
#define DESTROY_QP_HAS_UDATA
#define DEVICE_OPS_HAVE_ABI_VER
#define DEREG_MR_HAS_UDATA
#define ALLOC_MR_HAS_UDATA
#define HAVE_CORE_ALLOC_AH
#define HAVE_IBDEV_INIT_PORT

#include "compat_common.h"

#endif //RH82_COMPAT
